name: TrueCare2u_flutter
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.1 <3.0.0"
  flutter: ">=1.12.13+hotfix.6"

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  # maps
  google_maps_flutter: ^2.1.1
  location: ^4.3.0
  geocode: ^1.0.1
  flutter_google_places: ^0.3.0
  provider: ^6.0.1
  geolocator: ^8.0.1

  #font templates
  cupertino_icons: ^1.0.4
  font_awesome_flutter: ^9.2.0
  badges: ^2.0.2
  flutter_masked_text2: ^0.9.1

  # data network
  device_info: ^2.0.3
  http: ^0.13.4
  package_info: ^2.0.2

  # config
  flutter_secure_storage: ^5.0.2
  shared_preferences: ^2.0.11

  # migrate
  fluttertoast: ^8.0.8


  # firebase

  firebase_auth: ^3.3.12
  firebase_core: ^1.17.1
  cloud_firestore: ^3.1.4
  firebase_messaging: ^11.2.12
  #  crypto: 2.1.4
  # signin method
  # flutter_facebook_login: ^3.0.0
  google_sign_in: 5.3.2

  # agora
  agora_rtc_engine: ^5.0.0
  permission_handler: ^8.3.0

  # api
  dio: ^4.0.4
  #  dio_http_cache: ^0.2.4

  # date
  intl: ^0.17.0

  # freshchat
  localstorage: ^4.0.0+1
#  flutter_freshchat: 1.4.0
  freshchat_sdk : ^0.9.7

  # web
#  flutter_webview_plugin:
  url_launcher: ^6.0.17
  pdf_render: ^1.0.17
  flutter_cache_manager: ^3.3.0

  # message
  # emoji_picker: ^0.1.0
  firebase_storage: ^10.2.3
  cached_network_image: ^3.2.0
  image_picker: ^0.8.4+4

  # audio
  flutter_ringtone_player: ^3.1.1

  wakelock: ^0.5.6
  new_version: ^0.2.3
#  forceupdate: ^0.0.6
  advance_pdf_viewer:
  flutter_svg: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  english_words: ^4.0.0

flutter_icons:
  image_path: "images/logo.jpg"
  android: true
  ios: true
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    # tnc
    - assets/tnc/TC2U-Privacy-Policy.pdf
    - assets/tnc/TC2U-Terms-of-Services.pdf
    - assets/tnc/TC2U-Terms-of-Use.pdf
    - assets/images/splashscreen.png
    - assets/images/logo.png
    - assets/images/splash_logo.png
    - assets/icon/nurse.png
    - assets/icon/doctor.png
    - assets/icon/physiotherapy.png
    - assets/icon/live.png
    - assets/icon/mother.png
    - assets/icon/cart.png
    - assets/icon/diagnosis.png
    - assets/icon/blood.jfif
    - assets/car_icon.png
    - assets/images/send.png
    - assets/icon/default-profile.png
    - assets/images/PainScale.jpg
    # newicon
    - assets/iconnew/diagnosis.png
    - assets/iconnew/doctor.png
    - assets/iconnew/online.png
    - assets/iconnew/icon-tele-dietitian.png
    - assets/iconnew/icon-tele-psychologist.png
    - assets/iconnew/icon-tele-specialist.png
    - assets/iconnew/mother.png
    - assets/iconnew/nurse.png
    - assets/iconnew/physiotherapy.png
    - assets/images/highlights-box.png
    # menubar
    - assets/Menubar/icon-menubar-account-dark.png
    - assets/Menubar/icon-menubar-account-light.png
    # account
    - assets/Account/icon-account-profile.png
    - assets/Account/icon-account-password.png
    - assets/Account/icon-account-TnC.png
    - assets/Account/icon-account-settings.png
    - assets/Account/icon-account-logout.png
    - assets/Account/icon-account-family-member.png
    # menubar
    - assets/Menubar/icon-menubar-account-dark.png
    - assets/Menubar/icon-menubar-appointment-dark.png
    - assets/Menubar/icon-menubar-home-dark.png
    - assets/Menubar/icon-menubar-message-dark.png
    - assets/Menubar/icon-video-dark.png
    - assets/images/doctor-services.png

    # logo
    - assets/images/truecare2u-logo-1.png

    # onboarding
    - assets/onboarding/Onboarding-1.png
    - assets/onboarding/Onboarding-2.png
    - assets/onboarding/Onboarding-3.png
    - assets/onboarding/Onboarding-4.png
    - assets/onboarding/Onboarding-5.png

    # icons for others
    - assets/iconnew/Coming-soon.png

    # testiconvideocall
    - assets/test/add.svg
    - assets/test/arrow_left.svg
    - assets/test/endcall.svg
    - assets/test/flip.svg
    - assets/test/logog.svg
    - assets/test/message_circle.svg
    - assets/test/mic.svg
    - assets/test/video_camera.svg
    - assets/test/video.svg
    - assets/test/bg.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages